### ISSUE TITLE
Driver ec-e100 not found

### ISSUE THREAD

**Issue by robochime** [sittner/ec-debianize#5]
Hello Sasha,
until now I installed the code from IGH, now I would like to use your ec-debianize version, I have a clean installation of linux 4.9.0-5-rt-686-pae with Debian 4.9.65 and a network card 82557 Ethernet Pro 100 with the e100 drivers installed and it works correctly, your ec-debianize installation installs without problems, when I edit the / etc / default / ethercat file I add DEVICE_MODULES = e100, then update-ethercat-config and error in module ec-e100 not found, Do you know how I can solve it? with the configuration DEVICE_MODULES = generic works
I also find myself when I run linuxcnc error / dev / EtherCAT0: permission denied, why does this happen to me?
Thank you
Chimeno

**Comment by sittner** [comment]
Hello Chimeno,

DEVICE_MODULES = generic is the intended setting for rt_preeamt. The patched specialized drivers semms to be not updated annymore.

There is a group called "ethercat". Please add the relevant user to this group.

Regards
Sascha

**Comment by robochime** [comment]
hi Sasha,
changed the configuration:
DEVICE_MODULES = generic
KERNEL == "EtherCAT [0-9] *", MODE = "0664", GROUP = "users"
It works very well, thank you very much

regards
Chimeno

**Comment by sittner** [comment]
It would be better to leave the device belong to the ethercat group and add the user to this group.

**Comment by robochime** [comment]
Hello Sasha,
thanks for the answer I will change it:
- KERNEL == "EtherCAT [0-9] *", MODE = "0664", GROUP = "ethercat"
-sudo usermod -a -G ethercat cnc

Thank you
Chimeno
